spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5546/products_db
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:5555/
